import type { GuideBlock } from './types';

/**
 * Playbook bodies, keyed by item title.
 *
 * Before this file existed, `Guides` rendered 24 titles with read-time
 * estimates for articles that were never written, and the item buttons had no
 * onClick. "Complete stage playbook library" was a Builder feature that
 * resolved to nothing.
 */
export const GUIDE_CONTENT: Record<string, GuideBlock[]> = {
  // ── VALIDATION ───────────────────────────────────────────────────────────
  'The five-question idea filter': [
    { kind: 'text', body: 'Most ideas die from being interesting rather than being wrong. This filter is designed to kill an idea in twenty minutes so you do not spend six months finding out slowly.' },
    { kind: 'steps', heading: 'Run these in order', items: [
      'Who exactly loses money, time or standing if this problem stays unsolved? If you cannot name a person, you have a topic, not a business.',
      'What are they doing about it today? Every real problem already has an ugly workaround — a spreadsheet, a nephew, a WhatsApp group. If there is no workaround, there is probably no pain.',
      'How often does the pain happen? Weekly pain builds a business. Annual pain builds a project.',
      'Can you reach fifty of these people in the next fourteen days without paying for ads? Trade groups, estate WhatsApp groups, market associations, a supplier who already sells to them.',
      'What is the smallest thing you could charge for next week? Not the vision — the first invoice.',
    ] },
    { kind: 'callout', body: 'If you answer three or fewer with specifics, stop. The idea is not disqualified, but you do not yet know enough to spend money on it.' },
    { kind: 'text', body: 'The trap to avoid: answering question one with a demographic. "Young professionals in Lagos" is not a buyer. "Salon owners in Surulere who turn away walk-ins because they cannot track bookings" is a buyer, because you can go and find eleven of them this week.' },
  ],
  'Define one buyer, not a market': [
    { kind: 'text', body: 'A market is something you describe in a pitch deck. A buyer is someone you can message tonight. Until you have the second one, outreach stays vague and every message you write sounds like every other message they ignore.' },
    { kind: 'steps', heading: 'Narrow in three passes', items: [
      'Person: their role and their constraint, not their age bracket. "Owner-operator with two staff" beats "SME".',
      'Moment: the specific trigger that makes the problem urgent this week. Restock day. Month-end reconciliation. The day a rider disappears with goods.',
      'Consequence: what it costs them when it goes wrong, in naira or in reputation. If you cannot state this, you cannot price.',
    ] },
    { kind: 'text', body: 'Write the result as one sentence and put it where you will see it: "I help [person] who [moment] stop [consequence]." If the sentence needs a comma-separated list to feel complete, you have not narrowed enough.' },
    { kind: 'callout', body: 'Narrowing feels like shrinking the opportunity. It is the opposite — it is the only thing that makes cold outreach land, because the reader recognises themselves in the first line.' },
  ],
  'Praise versus purchase intent': [
    { kind: 'text', body: 'Nigerians are generous conversationalists. People will tell you your idea is beautiful, that God will bless it, that they will definitely patronise you. Almost none of that is data.' },
    { kind: 'list', heading: 'Praise — costs them nothing', items: [
      '"This is a good idea, well done."',
      '"I would definitely use something like this."',
      '"Send me the details, let me see."',
      '"When you launch, tell me."',
    ] },
    { kind: 'list', heading: 'Commitment — costs them something', items: [
      'Money, even a small deposit.',
      'Time on their calendar, scheduled, not "sometime".',
      'Reputation — a referral to a named person, with the intro sent while you are there.',
      'Access — they show you their actual records, prices or supplier list.',
    ] },
    { kind: 'text', body: 'After every conversation, write one line: what did this person actually give up? If the answer is nothing, the conversation was pleasant and uninformative. Three praise conversations mean nothing. One person transferring ₦5,000 before you have built anything means a great deal.' },
    { kind: 'callout', body: 'The strongest signal in Nigerian small business is unprompted repeat contact. If they message you first, a second time, without you chasing — that is real.' },
  ],
  'Book ten interviews in seven days': [
    { kind: 'text', body: 'Ten conversations is enough to hear the same sentence three times, which is the point at which you stop guessing. The barrier is never willingness — people enjoy talking about their work. The barrier is a vague ask.' },
    { kind: 'steps', heading: 'The seven-day sequence', items: [
      'Day 1: list thirty names. Warm contacts, second-degree intros, people whose shops you pass, members of trade groups you are already in.',
      'Day 1–2: message fifteen. Ask for fifteen minutes, name the topic, and be explicit that you are not selling.',
      'Day 3: go physical. Three shops or offices, mid-morning on a weekday when traffic is low. In-person conversion beats DMs by a distance.',
      'Day 4–5: follow up once with anyone who read and did not reply. Once. Not three times.',
      'Day 6–7: run the conversations you booked and write notes within an hour of each.',
    ] },
    { kind: 'callout', heading: 'A message that works', body: '"Good afternoon ma. I am researching how [specific business type] handle [specific problem] — I am not selling anything. Could I ask you four questions for fifteen minutes this week? Any day that suits you."' },
    { kind: 'text', body: 'Expect roughly a third to say yes. Fifteen messages plus three walk-ins reliably produces ten conversations. If your yes-rate is far below that, your message is too long or too vague about what you want.' },
  ],
  'Questions that reveal real pain': [
    { kind: 'text', body: 'The wrong question is hypothetical: "Would you use an app that tracks your stock?" Everyone says yes. The right question is historical: it asks what they actually did, when, and what it cost.' },
    { kind: 'list', heading: 'Replace hypothetical with behavioural', items: [
      'Instead of "would you pay for this" — "What did you spend money on last month to deal with this?"',
      'Instead of "is this a problem" — "Walk me through the last time this went wrong. What happened that day?"',
      'Instead of "what features do you want" — "What did you try before? Why did you stop?"',
      'Instead of "how much would you pay" — "What does an hour of this problem cost you?"',
    ] },
    { kind: 'text', body: 'Then stay quiet. The most valuable information in these conversations arrives in the silence after you stop talking. Count to five before filling it.' },
    { kind: 'callout', body: 'Never pitch during a discovery conversation. The moment you describe your solution, the person switches from informant to polite audience, and everything after that is contaminated.' },
    { kind: 'text', body: 'Record the exact words people use. Not your summary of them — their phrasing. That phrasing becomes your outreach copy later, and it will outperform anything you write yourself.' },
  ],
  'Turn interviews into a pilot': [
    { kind: 'text', body: 'A pilot is not a beta and not a favour. It is the smallest paid version of the thing, delivered to a real buyer, with a defined end date.' },
    { kind: 'steps', heading: 'From notes to pilot', items: [
      'Find the sentence that repeated. Across ten conversations, one complaint will appear at least four times, in similar language. That is your pilot.',
      'Scope it to one outcome deliverable in two weeks. Not a platform. One outcome.',
      'Price it low but not free. Free removes the only signal you are trying to buy.',
      'Name the end date and the success measure before you start. "By the 20th, you will have X, and we will know it worked if Y."',
      'Sell it to three people from your interview list — the ones who gave you commitment, not praise.',
    ] },
    { kind: 'callout', body: 'Charging a small amount is not about revenue. It is the cheapest way to find out whether the problem is worth solving, and it changes how seriously the buyer treats the pilot.' },
    { kind: 'text', body: 'If nobody from your interview list will pay a reduced price for a narrow version, that is a finding, not a failure. It usually means you found a real annoyance rather than a real cost. Go back to the notes and look for the one with a naira figure attached.' },
  ],

  'Size the opportunity on one page': [
    { kind: 'text', body: 'Before you spend weekends on an idea, check that the prize is big enough to be worth the effort. You do not need a market report. You need one page, a calculator and honest numbers you can defend to a friend who sells for a living.' },
    { kind: 'steps', heading: 'Fill in five lines', items: [
      'Reachable buyers: how many people who fit your one buyer can you actually reach in the next three months? Count real channels: your estate group, your office, two market associations, a supplier list. Not "everyone in Lagos".',
      'Buyers who will try it: of those, how many would realistically pay once? Start low. One in twenty is a reasonable working guess for a stranger; you will replace it with real numbers after your first test.',
      'Price per sale: what one customer pays you per order, in naira.',
      'Margin per sale: price minus what each order costs you to deliver, including transport, packaging, data and POS or transfer charges. Not the cost of the item alone.',
      'Repeat rate: how many times a month or a year a good customer buys again.',
    ] },
    { kind: 'text', body: 'Multiply it out. Say you plan to sell home-made zobo in 1.5-litre bottles. You can reach 600 people across your estate, office and church groups. One in twenty buys, so 30 customers. Each bottle sells for ₦2,500 and costs you ₦1,400 to make and deliver, so ₦1,100 margin. A good customer buys twice a month. That is 30 × 2 × ₦1,100 = ₦66,000 a month in margin before your own time.' },
    { kind: 'text', body: 'Now ask the real question: is ₦66,000 a month worth the Saturdays, the Lagos traffic and the evenings answering WhatsApp? Your answer may be yes, because it pays your fuel and data. It may be no, in which case you either find a larger reachable group, a higher-margin product or a different idea.' },
    { kind: 'list', heading: 'Where the maths usually lies', items: [
      'Counting the whole city instead of people you can reach this quarter.',
      'Using the selling price instead of the margin.',
      'Assuming everyone repeats. Most first buyers do not.',
      'Forgetting your own hours. A business that pays ₦40,000 for 60 hours of work is paying you less than many jobs.',
    ] },
    { kind: 'callout', body: 'Keep this page. After your first demand test, replace every guess with what actually happened. The page you wrote before the test is a hypothesis; the page after it is a decision.' },
  ],
  'Test demand on WhatsApp Status': [
    { kind: 'text', body: 'Your contacts already watch your Status. That makes it the cheapest demand test available to most side hustlers: no ad spend, no website, results inside a day. The aim is not views. The aim is to count how many people ask to buy.' },
    { kind: 'list', heading: 'How the tools behave', items: [
      'Status: each update disappears after 24 hours and is only shown to people who have saved your number, and whose number you have saved. With read receipts on, you can see who viewed it.',
      'Broadcast lists: one message goes to many people as separate private chats, up to 256 contacts per list. Only people who have saved your number receive it, and replies come back to you privately.',
      'Groups: everyone sees everyone else. Good for social proof, bad when one loud person dismisses your offer in front of the room.',
    ] },
    { kind: 'steps', heading: 'Run a three-day test', items: [
      'Day one: post one clear offer on Status. A real photo, the price in naira, what it is for, and one instruction: "Reply BUY to order."',
      'Day two: post a second angle. A close-up, a customer use case, or a delivery area and day. Keep the price and the instruction the same.',
      'Day three: send the same offer to one broadcast list of people you know would care, such as colleagues or neighbours. Do not add them to a group without asking.',
      'Every evening, write three numbers: viewers, replies, and replies that asked about price, delivery or payment.',
    ] },
    { kind: 'text', body: 'Read the result in this order. Buying questions beat compliments. "How much to Ajah?" and "Can I pay on delivery?" are real interest. "Nice one" and a heart emoji are not. If one hundred people viewed and nobody asked a buying question, the offer, the price or the audience is wrong. Change one thing and run it again.' },
    { kind: 'callout', body: 'WhatsApp has been testing monthly limits on broadcast messages in some countries, including messages to people who do not reply. Send to people likely to respond, keep lists small and relevant, and check the WhatsApp Help Centre if your broadcasts stop delivering.' },
  ],
  'Pre-sell before you produce': [
    { kind: 'text', body: 'The most expensive way to test an idea is to buy stock first. The cheapest way is to sell first and produce second. A paid pre-order tells you more than any survey, because the buyer has put money where their mouth is.' },
    { kind: 'text', body: 'Pre-selling works for most small offers: a batch of ankara bags, a cake for a specific date, a tutoring slot, a set of custom tees for an office event, a monthly cleaning plan for an estate. If you can describe it clearly and give a delivery date, you can pre-sell it.' },
    { kind: 'steps', heading: 'Set up the pre-order', items: [
      'Decide the batch size you can actually deliver well. Small is fine. Ten paid orders is a strong signal.',
      'Fix a delivery date you can keep with Lagos traffic and supplier delays included. Add a buffer of several days.',
      'Ask for a deposit or full payment. A deposit of half is common for made-to-order goods; full payment works for low-priced items.',
      'Take payment by bank transfer to a dedicated account or by a payment link, so every naira is traceable. Send a short receipt on WhatsApp for each payment.',
      'Set a closing date for orders. "Orders close Friday 6pm" turns interest into decisions.',
    ] },
    { kind: 'list', heading: 'Write these down before you collect a kobo', items: [
      'What exactly the customer is getting, with a photo or sample.',
      'The delivery date and area, and who pays for delivery.',
      'What happens if you cannot deliver: full refund within an agreed number of days.',
      'Your name and phone number on every receipt.',
    ] },
    { kind: 'callout', body: 'Only take money for what you are confident you can deliver. If the batch does not fill by the closing date, refund everyone promptly and say why. A clean refund protects your name, and in a small community your name is the business.' },
    { kind: 'text', body: 'Count the result plainly. If you hit your batch size, you have demand and the cash to produce. If you got half, you have a smaller business than you hoped, or the wrong price. If you got none, you have saved yourself the cost of the stock.' },
  ],
  'A ₦10,000 demand test': [
    { kind: 'text', body: 'Free tests reach people who already like you. A small paid test reaches people who owe you nothing, which is closer to how a real business works. Fix the budget at ₦10,000, decide in advance what result means yes, and do not top it up halfway.' },
    { kind: 'list', heading: 'Ways to spend the ₦10,000', items: [
      'A small sample batch given to strangers who match your buyer, in exchange for honest feedback and a chance to order.',
      'Flyers with a WhatsApp number at one estate gate, one market or one office complex.',
      'A boosted post on a social platform aimed at one city area. Check the current minimum spend in the app before you plan around it.',
      'Transport and data for a day of visiting ten shops that fit your buyer, with a printed one-page offer.',
    ] },
    { kind: 'steps', heading: 'Run it in four steps', items: [
      'Write your pass mark before you spend. For example: "At least 5 people ask for price and at least 2 pay." Without a pass mark, any result can be talked into a success.',
      'Use one offer, one price and one way to respond, such as a dedicated WhatsApp number or a code word, so you can tell which replies came from the test.',
      'Run it for a fixed window: seven days is enough for most offers.',
      'Record every reply in one sheet: date, source, what they asked, whether they paid.',
    ] },
    { kind: 'text', body: 'Then do the maths. Say the ₦10,000 brought 18 replies, 6 serious enquiries and 2 paid orders. Your cost to win one paying customer was ₦5,000. If each order earns you ₦3,000 in margin and customers rarely repeat, this channel loses money. If they repeat monthly, it may be worth it. The test does not tell you yes or no. It tells you what a customer costs.' },
    { kind: 'callout', body: 'Read the result honestly. If you missed the pass mark, do not explain it away with the weather, the fuel price or the algorithm. Change one thing, such as the offer, the price or the audience, and run another fixed test.' },
  ],
  'Test price with three numbers': [
    { kind: 'text', body: 'Most new sellers price by guessing what feels polite, then struggle to raise it later. Before you print a price list or set up a catalogue, find out what people will actually pay. You need three numbers, not a pricing theory.' },
    { kind: 'steps', heading: 'Find the three numbers', items: [
      'The floor: your full cost per order, including materials, packaging, transport, transfer or POS charges and a fair amount for your time. Below this, every sale loses money.',
      'The market: what buyers already pay for the closest alternative. Check three real sellers in your area, on WhatsApp, Instagram or in the market, and write down their actual prices, not their ads.',
      'The test price: a price above the floor that you will offer to real buyers and watch closely.',
    ] },
    { kind: 'text', body: 'Say you sell small-chops packs for office birthdays. Your floor is ₦3,200 a pack. Similar sellers charge between ₦4,000 and ₦5,500. Do not start at ₦4,000 because it feels safe. Offer ₦4,800 to the first ten enquiries and record what happens.' },
    { kind: 'list', heading: 'How to read the reaction', items: [
      'Everyone pays without a question: you are probably too cheap. Raise the price for the next ten.',
      'Most pay, a few haggle: you are close. Hold the price and add a small extra for larger orders instead of discounting.',
      'Most ask for a discount and then disappear: the price is high for this buyer, or the offer is not clear enough.',
      'Nobody replies at all: price may not be the problem. Check the offer and the audience first.',
    ] },
    { kind: 'callout', body: 'Price on paid orders, not on opinions. Asking "How much would you pay for this?" produces polite, low answers. Offering a real price and watching who transfers money produces the truth.' },
    { kind: 'text', body: 'Change the price in steps between batches, not inside the same conversation. Write each price, how many people saw it and how many paid in one sheet. After three rounds, you will have a price you can defend.' },
  ],
  'CAC business name registration in plain English': [
    { kind: 'text', body: 'Registration does not create demand, so do not let it delay your first sale. But once people are paying you, a registered name makes it easier to open a business bank account, apply to supply offices and look credible to new customers. This guide covers the basics. Confirm anything specific to your situation on the CAC website or with an accredited agent.' },
    { kind: 'list', heading: 'What you are choosing between', items: [
      'Business name: for a sole trader or partners trading under a name. The owner and the business are legally the same person, so the owner is personally responsible for its debts. Simplest and cheapest option.',
      'Private limited company: a separate legal person with its own obligations. Worth discussing with a lawyer or accountant once you have partners, investors, larger contracts or real liability risks.',
    ] },
    { kind: 'text', body: 'Under the Companies and Allied Matters Act 2020, you are expected to register a business name if you trade under a name that is not your own true name. "Ngozi Okafor" selling cakes does not need to register that name. "Ngozi Bakes" does. The law expects registration before, or soon after, you start trading under the name.' },
    { kind: 'steps', heading: 'How the online process works', items: [
      'Create an account on the CAC Company Registration Portal, reached from cac.gov.ng.',
      'Search for your proposed name and reserve one that is available. Have a second and third choice ready.',
      'Fill in the business name registration form with your business details, address and proprietor information.',
      'Upload images of your means of identification, passport photograph and signature.',
      'Pay the filing fee online through the portal. Check the current fee on the CAC portal before you start, and be wary of anyone quoting a price far above it.',
      'When approved, download your certificate and status report from your dashboard.',
    ] },
    { kind: 'callout', body: 'Registration comes with ongoing duties. Registered business names must file annual returns with CAC, and late filing attracts penalties. Put a yearly reminder in your phone the day your certificate arrives.' },
    { kind: 'text', body: 'You can register on your own without a lawyer. If you have partners, plan to hire staff or are unsure which structure fits, pay for an hour with an accredited agent or lawyer. It costs less than fixing the wrong structure later.' },
  ],
  'Separate business money from personal money': [
    { kind: 'text', body: 'If your customers pay into the same account as your salary, you cannot tell whether the business is making money. Every transfer for fuel, foodstuff and family support blurs the picture. The fix is simple and costs almost nothing: one account and one record.' },
    { kind: 'steps', heading: 'Set it up this week', items: [
      'Open a second account used only for the business. While you are still validating, a second personal account at your bank or a digital bank is enough. A business account in a registered name can come later, and each bank will give you its own list of required documents.',
      'Give that account number to customers and no other. Remove your salary account from your Status, flyers and WhatsApp catalogue.',
      'Pay every business cost from that account: stock, packaging, delivery riders, data for the business line.',
      'Pay yourself on purpose. Move a fixed amount to your personal account on a fixed day, and record it as owner pay, not as a business expense.',
    ] },
    { kind: 'list', heading: 'Your one simple record', items: [
      'Date.',
      'Money in or money out.',
      'Amount in naira.',
      'Who or what it was for: customer name, supplier, rider.',
      'Category: sale, stock, delivery, other cost, owner pay.',
    ] },
    { kind: 'text', body: 'Update it every evening from your bank alerts, not from memory. Five minutes a day is easier than an hour of reconstructing a month of POS slips and transfers. At month end, add up money in from sales and money out on costs. What remains before owner pay is what the business actually earned.' },
    { kind: 'callout', body: 'Do not lend business money to yourself or family "just until month end". It is the most common way small businesses that look busy end up with nothing. If you must use it, record it, and pay it back on a date.' },
    { kind: 'text', body: 'Clean records also make later steps easier: talking to an accountant about tax, applying for a loan, or showing a supplier you are serious. When your numbers grow, ask an accountant what records you need to keep for tax.' },
  ],

  // ── LAUNCH ───────────────────────────────────────────────────────────────
  'Your first ten clients': [
    { kind: 'text', body: 'The first ten almost never come from strangers on the internet. They come from people who already have a reason to trust you, and from the people those people know. Build the rhythm before you build the funnel.' },
    { kind: 'steps', heading: 'The weekly rhythm', items: [
      'Monday: five warm messages. People who already know you. Not a pitch — a specific, relevant observation plus an offer.',
      'Tuesday: five second-degree asks. "Do you know anyone who [specific situation]?" Named referrals beat broadcast posts.',
      'Wednesday: five cold, highly researched messages. Ten minutes of research each. Quality over volume, always.',
      'Thursday: follow up on everything from last week that went quiet.',
      'Friday: one piece of public proof — a result, a lesson, a short breakdown of how you solved something.',
    ] },
    { kind: 'text', body: 'Twenty conversations a week, sustained for six weeks, reliably produces the first few clients for most service businesses. The failure mode is not low conversion — it is stopping in week two because nothing happened in week one.' },
    { kind: 'callout', body: 'Track conversations started, not clients closed. The first number is under your control; the second is a lagging consequence of it.' },
  ],
  'Cold messages that earn replies': [
    { kind: 'text', body: 'Cold outreach fails for one reason: it is obviously about you. Four short parts fix that, and the whole message should fit on a phone screen without scrolling.' },
    { kind: 'steps', heading: 'The four parts', items: [
      'Observation — something specific and true about their business. It must be impossible to copy-paste to anyone else.',
      'Relevance — why that observation connects to something you do.',
      'Proof — one concrete result, with a number or a named situation. One line only.',
      'Easy next step — a small, low-commitment ask. Not "let us jump on a call."',
    ] },
    { kind: 'callout', heading: 'Example', body: '"Good morning — I noticed your Instagram shop takes orders in DMs but there is no price list in your highlights, so you are probably answering \'how much\' twenty times a day. I build simple order pages for fashion vendors; the last one cut a client\'s DM back-and-forth by about half. Would it help if I sent a one-page mockup for yours? No charge, no obligation."' },
    { kind: 'text', body: 'Never open with "I hope this message finds you well." Never send a voice note first. Never attach a deck to a first message. Every one of those signals a broadcast, and the reader files it accordingly.' },
  ],
  'Follow up without chasing': [
    { kind: 'text', body: 'Most deals are lost in silence rather than in rejection. But there is a real difference between persistence and pestering, and it is mostly about whether each follow-up carries new value.' },
    { kind: 'steps', heading: 'Three touches, then stop', items: [
      'Touch one, three days later: add something. A relevant example, a link, a thought about their specific situation. Do not ask "did you see my message?"',
      'Touch two, one week after that: change the channel. If you emailed, try WhatsApp. If you DM\'d, try a call.',
      'Touch three, two weeks after that: the close-the-loop message. "I am assuming the timing is not right — I will stop here. If it changes, my line is open."',
    ] },
    { kind: 'callout', body: 'The third message gets more replies than the first two combined. Removing pressure is what makes people respond.' },
    { kind: 'text', body: 'After touch three, stop and move the contact to a quarterly list. Reaching out once every three months with something genuinely useful keeps the door open for years. Messaging weekly closes it permanently.' },
  ],
  'Price the outcome': [
    { kind: 'text', body: 'Hourly pricing punishes you for getting better and forces the client to audit your time instead of your result. Move to packages as early as you can survive it.' },
    { kind: 'steps', heading: 'Building three tiers', items: [
      'Start from the outcome the buyer wants, then work backwards to what it is worth to them. What does the problem cost per month?',
      'Build the middle tier first — this is the one you actually want to sell.',
      'Build a lower tier that is genuinely useful but visibly narrower. It exists to make the middle look complete, and to catch buyers who cannot yet afford more.',
      'Build a higher tier with a small number of high-value additions. Some people will take it, which is a free lesson in what your market values.',
      'Name the tiers after outcomes, not sizes. "Order page live in seven days" beats "Basic".',
    ] },
    { kind: 'callout', body: 'Publish the starting price. In the Nigerian market, hiding prices reads as "expensive and about to negotiate", and it filters out the serious buyers along with the time-wasters.' },
    { kind: 'text', body: 'Expect discomfort the first three times you say the number out loud. Say it, then stop talking. Do not add "but we can discuss" before they have responded.' },
  ],
  'The 20-minute proposal': [
    { kind: 'text', body: 'Long proposals do not win work; they delay decisions. If you cannot fit it on one page, the scope is not clear enough yet.' },
    { kind: 'steps', heading: 'One page, six blocks', items: [
      'The situation, in their words. Quote them. This alone wins more work than anything else on the page.',
      'The outcome, stated as a result rather than a list of activities.',
      'What is included, in three to five bullets.',
      'What is explicitly not included. This prevents the scope argument three weeks in.',
      'Timeline with two dates: start and delivery.',
      'Price, payment terms, and exactly what happens next.',
    ] },
    { kind: 'callout', body: 'Send it as a PDF, not a document that can be edited. Send it within twenty-four hours of the conversation, while the problem is still emotionally live for them.' },
    { kind: 'text', body: 'End with a single clear instruction: "If this looks right, reply \'approved\' and I will send the invoice today." Ambiguous endings produce ambiguous replies.' },
  ],
  'Deposits and payment terms': [
    { kind: 'text', body: 'Cash flow kills more small Nigerian businesses than competition does. Payment terms are not admin — they are the part of the deal that determines whether you survive delivery.' },
    { kind: 'list', heading: 'Non-negotiables', items: [
      'Take a deposit before any work begins. Fifty percent is standard for project work; below thirty percent you are financing the client.',
      'Put the account details in the proposal, not in a later message. Friction between decision and payment loses deals.',
      'State a specific date for the balance, not "on completion" — completion is arguable, a date is not.',
      'Say what happens if payment is late, once, calmly, in writing. Usually: work pauses.',
      'Issue a proper invoice with your business name and a reference. It signals that you are a business, which changes how you get treated.',
    ] },
    { kind: 'callout', body: 'A client who will not pay a deposit is showing you exactly how the final payment will go. Take the information seriously.' },
    { kind: 'text', body: 'Wording that works without aggression: "To lock the start date I take 50% upfront, with the balance due on delivery day. I will send the invoice now and we can begin as soon as it clears."' },
  ],

  'Sell daily on WhatsApp Status': [
    { kind: 'text', body: 'Your contact list is the cheapest shop window you will ever have. The people who already have your number saved — colleagues, church members, old classmates, your estate group — check Status in traffic, on lunch break and before bed. Most side hustlers post once in a burst of excitement, then go quiet for two weeks. The ones who sell post every day, on a rhythm, so buyers start to expect them.' },
    { kind: 'text', body: 'Status updates disappear after 24 hours. That is the point: nothing you post has to be perfect, but anything you skip is simply missing. People generally need your number saved in their phone to see your Status, so ask every buyer and every new contact to save it.' },
    { kind: 'steps', heading: 'A daily rhythm of four posts', items: [
      'Morning, before 8am: one product photo with the price written on it. No price means fifty "how much?" messages and most of those people never reply again.',
      'Midday: proof. A delivery being packed, a screenshot of a customer thanking you (with their name and number hidden), a rider leaving with an order.',
      'Evening: a short explanation. How to use the product, what size to pick, the difference between your two options. Teach one thing.',
      'Late evening: the ask. "Three left at ₦12,500. Reply SEND to order, delivery tomorrow within Lekki and VI." One offer, one instruction, one deadline.',
    ] },
    { kind: 'list', heading: 'What kills Status sales', items: [
      'Twenty posts in a row. People tap past the whole block.',
      'Forwarded flyers from your supplier with someone else\'s number on them.',
      'No instruction. Every selling post should tell the viewer exactly what to type.',
      'Posting only when stock arrives. Silence teaches people to stop looking.',
    ] },
    { kind: 'callout', body: 'Check who viewed each post. A person who views your Status four days running and has never bought is a warm lead. Send them a short, personal message about the specific item, not a broadcast.' },
    { kind: 'text', body: 'Keep a simple tally for two weeks: posts made, replies received, orders closed. If the midday proof posts bring more replies than the product photos, post more proof. Let your own numbers tell you what your contacts respond to.' },
  ],
  'Build an offer people say yes to': [
    { kind: 'text', body: 'A product is what you sell. An offer is the full deal the buyer is deciding on: what they get, why they should believe it works, and what happens if it does not. Most early sellers post the product and a price, then wonder why people ask questions and disappear. The questions are the buyer trying to build the offer themselves. Do it for them.' },
    { kind: 'steps', heading: 'Build it in three layers', items: [
      'Outcome: describe the result, not the item. Not "small chops tray", but "small chops for 30 guests, delivered hot and set up before your guests arrive, so you are not in the kitchen at your own party."',
      'Proof: show that you have done this before. Two photos from past events, one message from a past client, the number of trays delivered last month. Specific and checkable beats impressive and vague.',
      'Guarantee: remove the fear that stops them paying. "If delivery is more than 30 minutes late, the next order is 10% off." Pick a promise you can afford to keep every single time.',
    ] },
    { kind: 'text', body: 'Then make the decision small. One price, at most three options, and a clear way to pay. "₦85,000 for 30 guests. ₦30,000 deposit locks your date, balance on delivery." A buyer who has to ask five questions to understand the deal is a buyer who will "get back to you".' },
    { kind: 'list', heading: 'Check your offer against these', items: [
      'Can someone understand it in one Status view, without asking anything?',
      'Is the result described in the words your buyer would use to a friend?',
      'Is there at least one piece of proof that is not your own claim?',
      'Is the guarantee something you can keep even on a bad day?',
      'Is there a clear next step — what to send, where to pay, by when?',
    ] },
    { kind: 'callout', body: 'Do not promise what you cannot control. A caterer can guarantee delivery time. A caterer cannot guarantee that guests will love the food. Guarantee the process, not the feeling.' },
  ],
  'Discounts without killing your margin': [
    { kind: 'text', body: 'A discount comes straight out of your profit, not your price. That is the part most side hustlers miss. If something costs you ₦6,000 to make and deliver and you sell it for ₦10,000, you make ₦4,000. Take 20% off the price and you sell at ₦8,000 — your profit halves to ₦2,000. You now need to sell twice as many just to stand still. These numbers are an example; run your own before you post any sale.' },
    { kind: 'list', heading: 'When a discount makes sense', items: [
      'Clearing slow stock that is tying up cash you need for faster-moving items.',
      'Getting a first order from someone who has watched you for weeks and not bought.',
      'Rewarding a bigger order that saves you a delivery trip or a supplier run.',
      'Filling a slow period, such as the weeks after January when budgets are tight.',
    ] },
    { kind: 'steps', heading: 'Always trade, never give', items: [
      'Work out your real cost per unit first, including packaging, delivery and POS or transfer charges. Never discount below this.',
      'Decide your floor price before any buyer asks. Write it down so you do not decide in the middle of a conversation.',
      'Ask for something in return: a bigger quantity, full payment upfront, pickup instead of delivery, or a review with a photo.',
      'Put an end date on it. "Till Sunday" is a reason to act. "For now" is not.',
    ] },
    { kind: 'callout', body: 'Prefer adding value over cutting price. Free delivery within your area, an extra small item or faster turnaround often costs you less than the naira discount and does not train buyers to wait for your next sale.' },
    { kind: 'text', body: 'Watch who your discounts attract. If most of your orders only come during promos, you have taught your customers that your normal price is not your real price. Run sales rarely, with a clear reason, and let your regular price stand the rest of the time.' },
  ],
  'A one-page presence that sells': [
    { kind: 'text', body: 'You do not need a website to start. You need three things that work together: a WhatsApp Business profile with a catalogue, an Instagram bio that says exactly what you sell, and one link that takes a stranger straight into a chat with you. Get those right and every post, flyer and referral has somewhere useful to land.' },
    { kind: 'steps', heading: 'Set it up in an evening', items: [
      'Switch to the WhatsApp Business app if you have not already. Fill in the business profile fully: logo or clear photo, short description, address or area served, opening hours and any website or Instagram link.',
      'Build your catalogue. Add each product with a clear photo, the price and a two-line description, and group similar items into collections. Start with your ten best sellers, not everything you have ever stocked.',
      'Set a greeting message for new chats and an away message for when you are at your day job, so nobody is left on read.',
      'Get your short link and QR code from the Business tools section of the app. This is the link that does the selling — it opens a chat with you directly.',
      'Write your Instagram bio in one line: what you sell, who it is for, and where. "Ready-to-wear ankara for working women. Lagos delivery in 48 hours." Put the WhatsApp link first.',
    ] },
    { kind: 'text', body: 'Instagram currently lets you add up to five links to your bio, but only the first shows without an extra tap. Make that first link your WhatsApp chat or your catalogue. Features change, so check the app settings if anything here looks different.' },
    { kind: 'callout', body: 'Test the whole path from a friend\'s phone. Tap the bio link, see the chat open, ask for a price, and time how long you take to answer. The slowest step in that journey is where you are losing buyers.' },
    { kind: 'list', heading: 'Keep it current', items: [
      'Remove sold-out items from the catalogue the same day.',
      'Update prices when your supplier prices change — wrong prices cost trust.',
      'Put the same short link on your flyers, packaging and email signature.',
    ] },
  ],
  'Invoices, receipts and simple records': [
    { kind: 'text', body: 'Clean paperwork does two jobs. It makes you look established, which makes people more willing to pay a deposit to someone they have never met. And it gives you records, which you will need when you want to know whether you are actually making money, and when the tax office asks.' },
    { kind: 'list', heading: 'What every invoice should show', items: [
      'Your business name, phone number and, if registered, your registration number.',
      'An invoice number that goes up in order — INV-001, INV-002 — never reused.',
      'The date, the customer name, and what they are buying, with quantity and unit price.',
      'The total, any deposit already paid, and the balance due with a due date.',
      'Payment details, with an account name that matches your business name if you can arrange it. A personal account with a different name makes buyers hesitate.',
    ] },
    { kind: 'steps', heading: 'A simple weekly routine', items: [
      'Send the invoice as a PDF or clear image before you start the job, not after.',
      'When money arrives, send a receipt the same day showing the amount, the date and the invoice number it settles.',
      'Log every sale and every expense in one place — a notebook, a spreadsheet or Nurj. Note the payment method: transfer, cash or POS.',
      'Every Sunday, check that what you logged matches what is in your account. Chase any unpaid invoice that is past its due date.',
    ] },
    { kind: 'text', body: 'Nigeria\'s new tax laws took effect on 1 January 2026. Under them, small companies below set turnover and asset limits do not charge VAT or pay company income tax, but the rules have conditions, and business names should check with an accountant which rules apply to them. Do not add VAT to your invoices unless you have confirmed you should. Your records are what prove which side of the line you fall on.' },
    { kind: 'callout', body: 'This is not tax advice. Once your sales are steady, spend an hour with an accountant to confirm your Tax ID, whether you need to charge VAT and what records to keep. It costs far less than fixing a problem later.' },
  ],
  'Collect testimonials that convince': [
    { kind: 'text', body: 'A stranger on WhatsApp has no reason to trust you. A real customer saying your product worked gives them one. But polished, generic praise reads as fake. The testimonials that convince are specific, a little rough, and clearly from a real person.' },
    { kind: 'steps', heading: 'Ask at the right moment', items: [
      'Ask when the customer is happiest: right after delivery, after the first wear, after the event went well. Not three weeks later when they have forgotten.',
      'Make it easy with a specific question: "What were you worried about before you ordered, and how did it turn out?" That gets a story, not "nice one".',
      'Ask for a photo or a short voice note if they are comfortable. A customer holding the product beats any studio shot.',
      'Ask permission in writing before you post anything: "Can I share your message on my Status? I will hide your number. Should I use your first name or keep it anonymous?"',
    ] },
    { kind: 'text', body: 'Permission matters. Nigeria\'s Data Protection Act 2023 treats names, photos and phone numbers as personal data. Consent must be clear — silence or not replying is not consent — and the person can withdraw it at any time. Keep the message where they said yes, and if they later ask you to take a post down, do it the same day.' },
    { kind: 'list', heading: 'Make proof feel real', items: [
      'Use their actual words. Fix nothing except obvious typos.',
      'Hide phone numbers and profile photos in screenshots unless they agreed to show them.',
      'Keep the detail: the area, the occasion, the problem it solved.',
      'Mix formats — screenshots, photos, voice notes — so it does not look manufactured.',
      'Never write a review yourself or ask friends to pose as customers.',
    ] },
    { kind: 'callout', body: 'Only share what is true and typical. ARCON, the advertising regulator, regulates online adverts and has warned against unverified claims. If a testimonial promises a result most customers will not get, leave it out. If you start paying for ads or influencers, check ARCON vetting rules with a lawyer first.' },
  ],
  'Handle "it is too expensive"': [
    { kind: 'text', body: 'When someone says "it is too expensive", they rarely mean the number is impossible. Usually they mean one of three things: they do not yet see why it is worth it, they are comparing you to something cheaper, or they cannot pay it all right now. Each needs a different answer, and none of them requires you to drop your price.' },
    { kind: 'steps', heading: 'Respond in this order', items: [
      'Ask before you answer: "Too expensive compared to what?" or "What budget did you have in mind?" Their reply tells you which of the three problems you are solving.',
      'If they cannot see the value, restate the outcome and the proof. "This includes setup and delivery to Ikeja, so you do not pay a rider or spend your Saturday on it. Here is one we did last week."',
      'If they are comparing, show the difference plainly. "The ₦8,000 one online is 1.5 metres. Ours is 2 metres, lined, and you can return it within three days."',
      'If it is cash flow, change the terms, not the price. Offer a deposit now and balance on delivery, or two instalments with the item released after the second.',
      'If none of that works, offer a smaller version at a lower price instead of the same thing for less money.',
    ] },
    { kind: 'callout', body: 'Every time you cut the price because someone pushed, you teach that buyer, and everyone they tell, that your first price was not real. Change what is included before you change the number.' },
    { kind: 'list', heading: 'Phrases that hold your ground politely', items: [
      '"I understand. Let me show you what is included, then you decide."',
      '"I cannot reduce it, but I can split the payment."',
      '"If budget is tight, the smaller set is ₦15,000 and does most of the same job."',
      '"No problem if it is not right for now. I will keep a slot for you till Friday."',
    ] },
    { kind: 'text', body: 'Some people will still walk away, and that is fine. A buyer who only wanted the cheapest option was never going to be your best customer. Track how often you hear the objection: if most people say it, your offer or proof needs work before your price does.' },
  ],

  // ── SCALING ──────────────────────────────────────────────────────────────
  'Raise prices without drama': [
    { kind: 'text', body: 'There are two separate problems here and conflating them causes most of the pain: what you charge new clients, and what you do about existing ones. Solve them separately.' },
    { kind: 'steps', heading: 'New clients', items: [
      'Raise the number on the next proposal you send. No announcement, no explanation, no apology.',
      'Hold it for five conversations before judging. One rejection is noise.',
      'If four of five say yes immediately, the price is still too low.',
    ] },
    { kind: 'steps', heading: 'Existing clients', items: [
      'Give at least thirty days notice, in writing, to each client individually. Never as a broadcast.',
      'State the new rate and the date it starts. Do not justify at length — one sentence of reason is enough.',
      'Offer to honour the old rate for work already scoped. This costs little and preserves the relationship.',
      'Expect to lose one. Budget for it emotionally before you send the messages.',
    ] },
    { kind: 'callout', heading: 'Script', body: '"From 1 [Month], my rate for this work moves to ₦X. Anything already agreed stays at the current rate. I have valued working with you and I hope we continue — I wanted to give you plenty of notice either way."' },
  ],
  'Package outcomes, not hours': [
    { kind: 'text', body: 'The purpose of a three-tier structure is not to offer choice. It is to change the question in the buyer\'s head from "should I buy this?" to "which one should I buy?"' },
    { kind: 'steps', heading: 'Designing the middle', items: [
      'The middle tier should contain everything a typical buyer actually needs. Nothing missing, nothing padded.',
      'The lower tier should be honestly narrower — a real option for a smaller buyer, not a crippled version designed to insult.',
      'The upper tier should be roughly two to three times the middle, with additions that only some buyers value. Speed, access, scope, or ongoing support.',
      'Price the middle at what the outcome is worth, then set the others around it. Never build up from cost.',
    ] },
    { kind: 'callout', body: 'If almost everyone picks the cheapest tier, the middle is not compelling enough. If almost everyone picks the middle, the structure is working.' },
    { kind: 'text', body: 'Review the mix every quarter. The tier nobody buys is telling you something — either it is priced wrong or it solves a problem your market does not have.' },
  ],
  'Find the work only you should do': [
    { kind: 'text', body: 'Scaling stalls when the founder is the bottleneck for everything. The unlock is not working harder — it is being precise about which decisions genuinely require you.' },
    { kind: 'steps', heading: 'The audit', items: [
      'Log everything you do for one week, in fifteen-minute blocks. Do not tidy it up.',
      'Mark each entry: judgment, relationship, craft, or admin.',
      'Admin goes first — it is the cheapest to hand off and the least risky to get slightly wrong.',
      'Craft goes second, once you have documented how you do it.',
      'Relationship and judgment stay with you the longest, and some of it stays forever.',
    ] },
    { kind: 'callout', body: 'The common mistake is delegating the work you dislike rather than the work that is genuinely low-leverage. Those are not the same list.' },
    { kind: 'text', body: 'Start with one task, not five. Document it, hand it over, accept that the first three attempts will be worse than yours, and correct rather than reclaim. Reclaiming teaches the person that you will always take it back.' },
  ],
  'Document one process in one hour': [
    { kind: 'text', body: 'Most process documentation fails because it is attempted at the wrong scale. You do not need a manual. You need one page for the one thing that breaks most often.' },
    { kind: 'steps', heading: 'The one-hour method', items: [
      'Pick the process that has gone wrong twice in the last month.',
      'Do it once, normally, while recording your screen or narrating a voice note as you go.',
      'Write the steps from the recording — not from memory. Memory skips the steps you do automatically, and those are exactly the ones a new person gets wrong.',
      'Add the three failure points and what to do at each.',
      'Have someone else follow it once without your help. Fix whatever confused them. Stop there.',
    ] },
    { kind: 'callout', body: 'A one-page SOP that people actually use beats a twenty-page manual that lives in a folder nobody opens.' },
    { kind: 'text', body: 'Store it somewhere the team already looks — a pinned WhatsApp message, a shared doc, a printed sheet on the wall. The best documentation is the one nearest to the work.' },
  ],
  'Projects into retainers': [
    { kind: 'text', body: 'Project income resets to zero every month and forces you to sell continuously. Retainers convert delivery into a base you can plan around, hire against, and eventually step back from.' },
    { kind: 'steps', heading: 'The conversion', items: [
      'Only propose it after a successful delivery, while the result is visible and recent.',
      'Anchor on the ongoing problem, not the ongoing work. "This will drift back within two months unless someone is watching it."',
      'Scope it tightly — a specific set of things, a specific frequency, a specific reporting rhythm.',
      'Price it at roughly a third of the project value per month for a comparable scope, then adjust with evidence.',
      'Set a review date at three months. Reviews make clients more willing to start, not less.',
    ] },
    { kind: 'callout', heading: 'The ask', body: '"Now that this is live, the thing that usually degrades is [specific]. I can hold that for you at ₦X monthly — [three specific deliverables], reviewed together every quarter. Want me to put it in writing?"' },
    { kind: 'text', body: 'Two retainers that cover your fixed costs change your negotiating posture on every project that follows. That shift is worth more than the retainer revenue itself.' },
  ],
  'A content system that compounds': [
    { kind: 'text', body: 'The goal is not reach. It is that the right person arrives at a conversation already believing you know what you are doing. One post a week, sustained for a year, does this. Daily posting for three weeks does not.' },
    { kind: 'steps', heading: 'The weekly unit', items: [
      'Take one real thing from your week — a problem you solved, a mistake, a number that surprised you.',
      'State the situation in two lines, with enough specificity that a peer recognises it.',
      'State what you did and why, including the part where you were unsure.',
      'State the outcome, with a number if you have one.',
      'Stop. No call to action, no engagement bait.',
    ] },
    { kind: 'callout', body: 'Specificity is the entire strategy. "How to grow your business" reaches nobody. "Why I stopped taking bank transfers without a reference and what it cost me first" reaches exactly the person who has that problem.' },
    { kind: 'text', body: 'Track one metric only: inbound conversations that mention something you wrote. Likes are not the product.' },
  ],

  'Your first hire or freelancer': [
    { kind: 'text', body: 'Most first hires fail before the person starts. The owner hires a cousin, a friend from church or whoever replied fastest on WhatsApp, with no written role, no test and no agreed pay. Three weeks later both sides feel cheated. A good first hire is a process, not a favour.' },
    { kind: 'steps', heading: 'Hire in four moves', items: [
      'Write the role on one page. List the five tasks that eat most of your week, the result you expect from each, and the hours. "Handle orders" is not a role. "Confirm every order within two hours, book dispatch and update the stock sheet by 6pm" is a role.',
      'Decide employee or freelancer. If the work is regular, on your schedule and under your direction, you are probably hiring staff. If it is a defined output they deliver on their own time, a freelancer fits. The legal duties are different, so decide before you advertise.',
      'Run a paid trial task. Give your top two or three candidates the same real task, a deadline and a fee, even ₦5,000 to ₦15,000. You learn more from one paid task than from three interviews, and paying shows you are serious.',
      'Agree terms in writing before day one. Pay, payment date, hours, what counts as done, notice period and who owns the work and customer contacts. A two-page letter both of you sign is enough to start.',
    ] },
    { kind: 'text', body: 'When you review the trial, score what you can see: did they meet the deadline, follow the brief, ask good questions and flag problems early? Polish matters less than reliability. A candidate who delivers 80 percent on time and tells you what they could not finish is worth more than one who delivers perfection three days late.' },
    { kind: 'callout', body: 'Never hire someone you cannot let go. If firing a relative or close friend would cause a family meeting, give them a fixed-term freelance task instead and keep the employment role for someone you can manage honestly.' },
    { kind: 'text', body: 'Budget for the first month as a cost, not a gain. You will spend more time training than you save. The payoff arrives in month two or three, once the checklist is written and they stop asking where things are. If you cannot afford three months of their pay from current profit, start with a freelancer on a defined task and revisit in a quarter.' },
  ],
  'Delegate without losing quality': [
    { kind: 'text', body: 'Many owners say "nobody does it like me" and then wonder why the business cannot grow past their own hours. The problem is usually not the staff. It is that the standard lives only in the head of the owner, so nobody else can meet it.' },
    { kind: 'steps', heading: 'Hand over a task properly', items: [
      'Pick one repeated task that takes at least three hours a week, such as packing orders, replying to enquiries or posting on Instagram.',
      'Record yourself doing it once. A voice note or a screen recording while you talk through each step is faster than writing a manual.',
      'Turn the recording into a checklist of no more than ten lines. Each line should be something a person can tick, not a feeling. "Wrap glass items in two layers of bubble wrap" beats "pack carefully".',
      'Show a good example and a bad example. A photo of a correctly packed parcel next to one that came back damaged teaches more than a paragraph.',
      'Let them do it while you watch once, then let them do it alone.',
    ] },
    { kind: 'text', body: 'After handover, your job changes from doing to inspecting. Inspecting means checking a sample against the checklist and giving one specific correction. Redoing means taking the work back and fixing it yourself. Redoing feels faster today, but it teaches the person that your standard is optional, because you will always clean up after them.' },
    { kind: 'list', heading: 'A simple inspection rhythm', items: [
      'Week one: check every piece of work.',
      'Weeks two to four: check one in five.',
      'After a month: spot-check weekly and review any customer complaint together.',
      'Whenever an error repeats: update the checklist, not just the person.',
    ] },
    { kind: 'callout', body: 'If the same mistake happens twice, the checklist is the problem. If it happens three times after the checklist is fixed, the person is the problem. Treat those two situations differently.' },
  ],
  'Staff, contractors and the law: the basics': [
    { kind: 'text', body: 'Once someone works for you regularly, you have legal duties, even if the business is small and the arrangement is informal. This is a plain-language starting point, not legal advice. Laws and rates change, so confirm the details with a lawyer, an accountant or the relevant agency before you act.' },
    { kind: 'list', heading: 'The core duties for employees', items: [
      'Written terms. The Labour Act expects an employer to give a worker a written statement of terms within three months of starting: pay and when it is paid, hours, leave, notice and the nature of the job. Give it on day one instead.',
      'PAYE. You deduct income tax from salary each month and pay it to the tax authority of the state where the employee lives, LIRS for Lagos residents. Employers must also file an annual return of all pay given to staff, due by 31 January; confirm the date with your state tax office.',
      'Pension. The Pension Reform Act 2014 covers private employers with three or more employees. The minimum is 10 percent from you and 8 percent from the employee, calculated on basic pay, housing and transport. Remit to the Pension Fund Administrator of each employee within seven working days of paying salary.',
      'Group life insurance. Employers under the pension scheme must also keep a group life policy for staff, with cover of at least three times annual total pay.',
      'Minimum wage. The national minimum wage is ₦70,000 a month since 2024. The law exempts establishments with fewer than 25 workers, but paying below it makes hiring and retention harder anyway.',
    ] },
    { kind: 'text', body: 'Contractors and freelancers are different. They invoice you for defined work, control how they do it and handle their own tax. Write a short contract that states the deliverable, the fee, payment terms and who owns the finished work. Be careful about calling someone a contractor when they work fixed hours, only for you, under your direction. That looks like employment, and the duties above may still apply.' },
    { kind: 'callout', body: 'Get professional help before your first payroll, before you hit three staff, and before you dismiss anyone. An hour with an accountant or employment lawyer costs far less than back pay, penalties or a dispute.' },
    { kind: 'text', body: 'Keep a file for every person: signed terms, ID, bank details, payslips and proof of each tax and pension remittance. If an inspector or a former staff member ever questions you, the file is your answer.' },
  ],
  'Know your numbers every month': [
    { kind: 'text', body: 'Revenue is the number everyone watches and the one that tells you least. A month with ₦2,000,000 in sales can still lose money if costs crept up, or leave you broke if customers have not paid. One hour on the first weekend of each month, with your bank statement and sales records, fixes this.' },
    { kind: 'steps', heading: 'The one-page monthly check', items: [
      'Sales: total value of what you sold last month, whether or not you have been paid.',
      'Direct costs: what you spent to deliver those sales, such as stock, materials, packaging and dispatch.',
      'Gross margin: sales minus direct costs, divided by sales. If you sold ₦2,000,000 and direct costs were ₦1,300,000, your gross margin is 35 percent.',
      'Running costs: rent, data, staff, ads, subscriptions and bank charges.',
      'Profit: gross margin in naira minus running costs. This is what the business actually earned.',
      'Cash: money in the business account on the last day of the month, plus what customers still owe you, minus what you owe suppliers.',
    ] },
    { kind: 'text', body: 'Write the six numbers in the same table every month so you can compare. One month tells you very little. Three months show a direction. Twelve months show seasons, such as the December rush or the slow weeks after school fees are paid.' },
    { kind: 'list', heading: 'Warning signs to act on', items: [
      'Gross margin falling for two months in a row. Your supplier prices or discounts are eating you.',
      'Profit positive but cash falling. Customers are paying late or stock is piling up.',
      'Running costs growing faster than sales. You are adding overhead before the business can carry it.',
      'You cannot tell personal spending from business spending. Separate the accounts first, then measure.',
    ] },
    { kind: 'callout', body: 'Pay yourself a fixed amount as a running cost, even a small one. If the business only looks profitable because you work for free, it is not yet profitable.' },
  ],
  'Small business tax basics under the 2025 tax laws': [
    { kind: 'text', body: 'Nigeria rewrote its tax laws in 2025. Most of the new rules took effect on 1 January 2026, and the Nigeria Revenue Service (NRS) replaced FIRS as the federal tax authority. Many small businesses pay less under the new rules, but the duty to register, keep records and file has become stricter. This is an overview, not tax advice.' },
    { kind: 'list', heading: 'What the new rules mean for you', items: [
      'Tax ID. Every taxable person must register and get a Tax ID. For individuals it is linked to your NIN, and for registered businesses to your CAC number. The law expects taxable persons to give banks their Tax ID, so get yours now and check with your bank what it needs.',
      'Small company status. A company with annual turnover of ₦100 million or less and fixed assets not more than ₦250 million is a small company. It pays 0 percent company income tax and is exempt from capital gains tax and the development levy. Professional services firms, such as law, accounting and consulting, do not qualify regardless of size.',
      'VAT. Small companies on the same test, except professional services firms, do not charge VAT. Above it, VAT is 7.5 percent and you must register, charge and file. If you trade as a business name, check with an accountant or the NRS which VAT threshold applies to you.',
      'Business names. If you trade as a business name or sole trader, profit is taxed as your personal income. The first ₦800,000 a year is taxed at 0 percent, then rates rise in bands from 15 percent to 25 percent above ₦50 million. You pay this to your state tax authority, LIRS in Lagos.',
    ] },
    { kind: 'callout', body: 'Exempt does not mean invisible. A company must still file its annual tax return even when it owes nothing. Not filing can attract penalties that cost more than the tax would have.' },
    { kind: 'steps', heading: 'Records to keep from today', items: [
      'Every sales invoice or receipt, numbered in order.',
      'Every expense receipt, with what it was for written on it.',
      'Monthly bank statements for the business account, kept separate from personal spending.',
      'Payroll records, PAYE and pension remittance receipts if you have staff.',
      'Keep all of these for at least six years, which is the period the tax administration law sets. Confirm with the NRS or an accountant if you are unsure.',
    ] },
    { kind: 'text', body: 'Use a tax consultant or accountant for your first return under the new rules, when you approach the ₦100 million turnover line, and before you hire staff. Rules and guidance from the NRS are still being issued, so check nrs.gov.ng or ask a professional before relying on any figure.' },
  ],
  'Get paid on time': [
    { kind: 'text', body: 'Late payment is the quiet killer of Nigerian small businesses. You deliver, the customer says "I will send it tomorrow", and tomorrow becomes three weeks. Meanwhile you are paying suppliers and staff from your own pocket. Most late payment is not malice. It is unclear terms and nobody asking.' },
    { kind: 'steps', heading: 'Set terms before you deliver', items: [
      'State the price, the due date and how to pay on every quote and invoice, not just in conversation.',
      'For new customers, take a deposit before you start. Fifty percent is normal for custom work and events.',
      'For repeat business customers, set a short term such as seven or fourteen days, and write it on the invoice.',
      'Send the invoice the same day you deliver. Every day of delay teaches the customer that payment is not urgent.',
    ] },
    { kind: 'list', heading: 'A reminder sequence that stays polite', items: [
      'Two days before due: "Hello Mrs Bello, a reminder that invoice 042 for ₦180,000 is due on Friday. Account details are below."',
      'On the due date: "Good morning, invoice 042 is due today. Kindly send proof of payment when done."',
      'Seven days late: a phone call, not a message. Ask for a specific date and amount, then confirm it in writing.',
      'Fourteen days late: pause further work or deliveries for that customer until the balance is cleared, and say so plainly.',
    ] },
    { kind: 'text', body: 'If thirty days pass with no payment and no plan, send a formal letter of demand stating the amount, the original due date and a final deadline. For larger sums, a letter on a lawyer letterhead often works where messages failed. Lagos State also runs a small claims court for simple debts, which requires a letter of demand first. Ask a lawyer whether your claim fits its current limit.' },
    { kind: 'callout', body: 'Chasing money is not rude. Delivering work you have not been paid for is a loan you never agreed to give. Be warm in tone and firm in action.' },
  ],
  'When to register a limited company': [
    { kind: 'text', body: 'Most side hustles start as a business name with the Corporate Affairs Commission (CAC), or with no registration at all. That is fine at the start. The question at the scaling stage is whether the business has outgrown that structure.' },
    { kind: 'list', heading: 'Business name versus Ltd', items: [
      'Liability. A business name is not a separate legal person. You and the business are the same, so business debts and lawsuits can reach your personal assets. A limited company is a separate legal person, so your liability is generally limited to what you put in.',
      'Credibility. Corporate clients, banks, government agencies and some platforms prefer or require a company. "Ltd" on an invoice can open doors that a business name cannot.',
      'Tax. Business name profit is taxed as your personal income. A company is taxed separately, and under the 2025 tax laws a qualifying small company pays 0 percent company income tax. Professional services firms are excluded from that relief.',
      'Ownership. A company can issue shares, so bringing in a partner or investor is cleaner. Since CAMA 2020, one person can own a private company alone.',
      'Paperwork. Both must file annual returns with the CAC, business names by 30 June each year. A company also needs proper accounts, a separate bank account and more formal records.',
    ] },
    { kind: 'text', body: 'Cost is higher for a company, but it is a one-off registration plus yearly filing and bookkeeping, not a fortune. The minimum issued share capital for a private company is ₦100,000. Filing fees change, so check the CAC portal for current charges rather than trusting an agent quote.' },
    { kind: 'steps', heading: 'Signs it is time to switch', items: [
      'A client or contract you want requires a registered company.',
      'You are signing leases, supplier credit or contracts large enough to hurt you personally if things go wrong.',
      'You are about to bring in a partner, investor or co-founder.',
      'Turnover is growing steadily and you want the business to outlive your personal involvement.',
    ] },
    { kind: 'callout', body: 'Do not register a company just to look big. Register when the protection, the clients or the ownership structure is worth the extra admin. When you decide, use a lawyer or accredited CAC agent and confirm the tax position with an accountant.' },
  ],

  // ── EXIT ─────────────────────────────────────────────────────────────────
  'Calculate your six-month runway': [
    { kind: 'text', body: 'Runway is the number that converts leaving your job from a feeling into a decision. Most people guess it, guess low, and leave at the wrong time.' },
    { kind: 'steps', heading: 'The calculation', items: [
      'Personal burn: rent or its monthly equivalent, food, transport, data, family obligations, health, and the irregular costs you forget — car repairs, occasions, black-tax months. Add fifteen percent for the ones you did not list.',
      'Business burn: tools, subscriptions, data, transport to clients, any help you pay for.',
      'Add both. Multiply by six. That is your floor.',
      'Subtract confirmed recurring revenue that will continue after you leave. Not hoped-for revenue — signed.',
      'The remainder is what must be in the bank before you resign.',
    ] },
    { kind: 'callout', body: 'Six months is the minimum for most people, not the target. Nine months buys you the ability to say no to bad clients, which is what actually determines whether the business survives year one.' },
    { kind: 'text', body: 'Recalculate monthly. The number moves as your recurring revenue grows, and watching it move is the most motivating dashboard you will ever build.' },
  ],
  'The salary replacement model': [
    { kind: 'text', body: 'Work backwards from what you need, not forwards from what you hope. The arithmetic is unglamorous and it is the whole plan.' },
    { kind: 'steps', heading: 'Working backwards', items: [
      'Start with your current take-home pay, not your gross. That is the number your life is built on.',
      'Add what your employer covers that you will now cover yourself — pension, health, transport, any allowances.',
      'Add tax on your business income. Do not skip this step; it is where most projections quietly break.',
      'Divide by your average monthly value per client. That is how many clients you need.',
      'Divide by your close rate to get conversations required per month. That is your actual weekly target.',
    ] },
    { kind: 'callout', body: 'If the number of clients required is uncomfortably high, the answer is almost always pricing, not effort. Doubling your price halves the number of relationships you must maintain.' },
    { kind: 'text', body: 'Then apply the retention check: what percentage of clients stay past three months? Replacement is not real until the base is stable, because churn means you are running to stand still.' },
  ],
  'Never let one client own your future': [
    { kind: 'text', body: 'A single client at sixty percent of revenue is not a great client relationship. It is an employer with none of the protections, and it will shape every decision you make in ways you will not notice until it ends.' },
    { kind: 'steps', heading: 'The concentration rule', items: [
      'No single client above forty percent of monthly revenue. Above that, you are structurally unsafe.',
      'Calculate the ratio on the first of every month. It moves faster than you expect.',
      'When one client crosses the line, do not fire them — outsell the concentration. Add clients rather than subtracting revenue.',
      'Keep prospecting during your best months. The instinct to stop when busy is what creates the concentration in the first place.',
    ] },
    { kind: 'callout', body: 'The warning sign is behavioural before it is financial: you start accepting scope changes you would refuse from anyone else. That is the concentration talking.' },
    { kind: 'text', body: 'If you are already concentrated, be honest about it and set a target date to get under forty percent. Naming the risk removes most of its power over your decisions.' },
  ],
  'Your 90-day exit countdown': [
    { kind: 'text', body: 'An exit date without weekly milestones is a wish. Ninety days is long enough to build a base and short enough to stay urgent.' },
    { kind: 'steps', heading: 'Three phases', items: [
      'Days 1–30, prove the engine: hit your weekly conversation target every week without exception. Do not optimise anything yet — establish that you can generate pipeline while employed.',
      'Days 31–60, build the base: convert to recurring where possible, raise prices on new work, and get runway into the account. Target sixty percent of salary replaced by day sixty.',
      'Days 61–90, de-risk and prepare: document your processes, confirm your runway number, write the resignation, and line up the first thirty days of work post-exit.',
    ] },
    { kind: 'callout', body: 'Two checkpoints are non-negotiable. Day 45: is recurring revenue growing month on month? Day 75: is the runway in the account, not projected? If either answer is no, move the date. Moving a date is not failure — leaving without a base is.' },
    { kind: 'text', body: 'Tell exactly one person the date. Accountability without an audience. A public announcement creates pressure to leave on schedule even when the numbers say otherwise.' },
  ],
  'Resign without burning the bridge': [
    { kind: 'text', body: 'Your employer is the single most likely first client of your new business, and the people you work with now will be referring you for the next decade. The exit is a commercial act, not just a personal one.' },
    { kind: 'steps', heading: 'How to leave well', items: [
      'Tell your direct manager first, in person or on a call, before anyone else hears it. This matters more than the notice period.',
      'Give full notice, and more if you can afford it. The extra weeks cost you little and buy you a great deal.',
      'Do not explain that you are leaving to build something better. "I am moving on to work on my own thing" is complete.',
      'Document your work and hand over properly. This is what people remember two years later.',
      'Never discuss grievances on the way out, however justified. There is no version of that conversation that helps you.',
    ] },
    { kind: 'callout', body: 'Wait at least a month before approaching your former employer as a client. Approaching immediately makes the resignation look like a sales tactic in retrospect.' },
    { kind: 'text', body: 'Keep the relationships warm afterwards. A short message twice a year to former colleagues, with something useful in it, is the highest-return networking available to you.' },
  ],
  'The first 30 days full-time': [
    { kind: 'text', body: 'The first month full-time is dangerous precisely because it feels free. Without the structure your job imposed, most people become reactive and busy, and produce less than they did while employed.' },
    { kind: 'steps', heading: 'Build structure before freedom', items: [
      'Keep working hours. Start and stop at fixed times. This is for the people around you as much as for you.',
      'Protect the first two hours for sales. Not admin, not building, not tidying the website. Pipeline first, every single day.',
      'Set a weekly review at a fixed time: conversations started, proposals sent, revenue closed, runway remaining.',
      'Leave the house at least three times a week. Isolation degrades judgment faster than anything else at this stage.',
      'Do not rebuild your brand, your logo or your site in month one. That is procrastination wearing a productive costume.',
    ] },
    { kind: 'callout', body: 'The most common month-one failure is spending it preparing to work rather than working. If you have not sent a proposal by day seven, that is what is happening.' },
    { kind: 'text', body: 'Expect a confidence dip somewhere around week three, usually after the first rejection with no salary behind it. It is normal, it passes, and the only reliable cure is another conversation booked.' },
  ],
  'Read your employment contract first': [
    { kind: 'text', body: 'Before you write a resignation letter, read the contract you signed and the staff handbook it refers to. Many people signed an offer letter on their first day and never looked at page four again. Page four is where the problems live.' },
    { kind: 'list', heading: 'Clauses to find and highlight', items: [
      'Notice period and pay in lieu. Note how much notice you must give, and whether the company can pay salary instead of keeping you for the notice period.',
      'Outside business. Some contracts require written approval for any other business, even one run at weekends. If you have been trading without approval, speak to a lawyer before you raise it with HR.',
      'Confidentiality. This usually continues after you leave. Customer lists, pricing, supplier terms and internal documents stay with the company.',
      'Non-compete and non-solicitation. Look for how long it lasts, what area it covers, which activities it restricts, and whether it stops you approaching former clients or colleagues.',
      'Intellectual property. Many contracts give the employer ownership of work created during employment, or on company time or equipment. If your product was built on the office laptop, that matters.',
      'Final entitlements. Leave days owed, any staff loan balance that will be deducted, and company property you must return.',
    ] },
    { kind: 'text', body: 'The Labour Act sets minimum notice periods, from one day to one month depending on length of service, but it covers mainly manual and clerical workers. If you are in a professional, technical or managerial role, your contract usually decides your notice.' },
    { kind: 'text', body: 'Nigerian courts treat a restraint on working after you leave as unenforceable unless the employer shows it is reasonable: a real interest to protect, such as trade secrets or client connections, and sensible limits on time and area. The Supreme Court has upheld a short restraint limited to a set area, in Koumoulis v Leventis Motors (1973), and the National Industrial Court has refused to enforce clauses that only stop someone using general skills. That does not mean you can ignore the clause. A company can still sue, and a case costs money and focus your business needs.' },
    { kind: 'callout', body: 'If your business serves the same customers, uses the same suppliers or does what your employer does, pay a lawyer to read the contract before you resign. One consultation costs far less than one dispute.' },
    { kind: 'text', body: 'Finish with one page: last working day, notice required, every restriction and how long it lasts. Plan your launch around that page, not around how you feel on a bad Monday.' },
  ],
  'Health cover, pension and savings after the payslip': [
    { kind: 'text', body: 'Your payslip did more than pay you. It probably carried an HMO plan, a pension contribution with an employer top-up, and perhaps leave allowance or a thirteenth month. On your last day, all of it stops, usually without a reminder.' },
    { kind: 'steps', heading: 'Before your last day', items: [
      'Ask HR for your HMO name, plan details and the exact date your cover ends.',
      'Get your pension PIN and the name of your Pension Fund Administrator (PFA). Check your RSA statement, not just your payslip, to confirm every deduction was actually remitted.',
      'Choose replacement health cover and start it before the old plan ends, so there is no gap.',
      'Set up a standing monthly transfer for pension and savings, timed for the day business income usually lands.',
    ] },
    { kind: 'text', body: 'Health cover. The National Health Insurance Authority Act 2022 makes health insurance mandatory for residents, and states run their own schemes. In Lagos, LASHMA runs Ilera Eko, with individual and family plans; other states have their own agencies. NHIA-accredited HMOs also sell individual and family plans. Compare which hospitals near you are on the list, what is excluded, how long before certain benefits start, and what to do in an emergency. Ask the HMO adviser to explain anything unclear before you pay.' },
    { kind: 'text', body: 'Pension. Your RSA belongs to you and stays open after you leave, with the same PIN. Ask your PFA how to keep paying in as voluntary contributions and what the access rules are. You can only have one RSA, so do not open a second one. Check with your PFA how to keep contributing to your existing RSA as a self-employed person, including under the Micro Pension Plan. The law also allows a one-time withdrawal of up to 25 percent of your balance if you are out of paid employment for four months and meet PenCom conditions. Ask your PFA whether you qualify, and treat it as a last resort, because it shrinks your retirement.' },
    { kind: 'list', heading: 'Keep three separate pots', items: [
      'Household emergency fund: at least six months of essential personal expenses, never mixed with business money.',
      'Health buffer: cash for what your plan does not cover.',
      'Retirement: a fixed amount every month, even ₦10,000, paid before you pay yourself anything extra.',
    ] },
    { kind: 'callout', body: 'Do this while you are still employed. Some plans have waiting periods for certain benefits, so cover bought in the month you fall ill may not pay for that illness.' },
  ],
  'Your personal tax once you leave PAYE': [
    { kind: 'text', body: 'For years your employer deducted tax before your salary landed, through PAYE. Once you leave, nobody deducts anything. You become responsible for declaring your income, filing a return and paying, every year.' },
    { kind: 'text', body: 'The rules changed on 1 January 2026, when the Nigeria Tax Act 2025 took effect. For individuals, the first ₦800,000 of taxable income is taxed at 0 percent, the next ₦2.2 million at 15 percent, the next ₦9 million at 18 percent, the next ₦13 million at 21 percent, the next ₦25 million at 23 percent, and anything above ₦50 million at 25 percent. There is also a rent relief of 20 percent of annual rent paid, capped at ₦500,000.' },
    { kind: 'steps', heading: 'Get set up', items: [
      'Confirm your Tax ID. Individuals get a 13-digit Tax ID linked to their NIN from the Tax ID portal, and a company registered with CAC gets one linked to its CAC number.',
      'Register with the tax authority of the state where you live. Self-employed people pay personal income tax to their State Internal Revenue Service: LIRS in Lagos through its eTax portal, FCT-IRS in Abuja, and so on.',
      'Open a separate business account. Every naira of income and every business expense should pass through it.',
      'Keep records every month: invoices, receipts for business expenses, bank statements, rent receipts, and proof of pension and health insurance payments.',
      'File by 31 March each year for the previous year, and confirm the date with your State Internal Revenue Service, such as LIRS in Lagos. In the year you resign, include both the salary you earned before leaving and the business profit after. Late filing attracts penalties and interest.',
    ] },
    { kind: 'text', body: 'A simple example. Your business sells ₦6,000,000 in a year and genuine business expenses come to ₦3,000,000, leaving ₦3,000,000 profit. Before any reliefs, the first ₦800,000 is tax-free and the remaining ₦2,200,000 is taxed at 15 percent, so the tax is ₦330,000. That is ₦27,500 a month. Move it into a separate account every month so March does not arrive as a shock.' },
    { kind: 'callout', body: 'This covers the basics only. If you are incorporating a company, earning in foreign currency, or unsure which expenses count, pay an accountant to prepare your first return. It is cheaper than correcting a wrong one.' },
  ],
  'Tell your family you are going full-time': [
    { kind: 'text', body: 'In many Nigerian homes, a stable job is more than income. It is proof that the sacrifices made for your education paid off, and it is what your parents mention at family meetings. When you say you are leaving it, some will hear that you are throwing that away. Their worry is usually love expressed as fear. Answer it with a plan, not with passion.' },
    { kind: 'steps', heading: 'Plan the conversation', items: [
      'Spouse first, and before anything is final. A spouse should help shape the decision, not hear it as news.',
      'Then parents, then the sibling, uncle or aunt whose opinion carries weight in the wider family, so nobody hears it second-hand at a party.',
      'Choose a quiet visit with time to talk, in person where possible. Not a rushed phone call, not in front of the whole compound.',
      'Start with thanks. Acknowledge what they invested in you, and make clear you are asking for support on a plan you have tested, not rejecting their advice.',
      'Show one page of numbers: what the business made over the last six months, your monthly household costs, how many months your savings cover, and that health cover and pension are arranged.',
      'Say plainly what changes for them. If you send money home every month, say whether that continues and at what amount. Families worry most about what nobody says aloud.',
      'Ask for one specific kind of support: introductions, prayers, patience, or an agreement to wait for the first check-in before judging.',
    ] },
    { kind: 'list', heading: 'Questions to prepare for', items: [
      '"What if it fails?" Give your fallback: the savings floor, and the date you will look for a job again if targets are missed.',
      '"Why not keep doing both?" Show what the business is turning down because of your working hours.',
      '"How will you take care of the home?" Walk through rent, school fees and food, line by line.',
    ] },
    { kind: 'callout', body: 'Know before you start whether you are asking for permission or for support. Both are honourable. Mixing them up is what turns a family conversation into a quarrel.' },
    { kind: 'text', body: 'One conversation rarely settles it. Agree a check-in three months after you resign and bring the same page, updated. Steady, honest updates turn worry into pride faster than any speech.' },
  ],
  'Build your support circle': [
    { kind: 'text', body: 'At work, structure came free: a manager, colleagues, deadlines, someone to greet in the morning. When you go full-time on the business, that disappears overnight. The first months are often quiet, and quiet is where doubt grows.' },
    { kind: 'list', heading: 'Four kinds of people you need', items: [
      'A mentor a few years ahead in a similar business. Not a celebrity. Someone who has solved the problem you face this quarter and will take a call once a month.',
      'Two or three peers at your stage, people leaving jobs or recently left. You share suppliers, leads and honest numbers.',
      'An accountability partner. One person you report your weekly targets to every Friday, who reports theirs to you.',
      'A professional bench: an accountant, a lawyer and a banker who knows your account. You will not need them weekly, but save their numbers before you need them.',
    ] },
    { kind: 'steps', heading: 'Build it in sixty days', items: [
      'List ten people you already know who run businesses: former colleagues who left, alumni groups, your church or mosque business fellowship, trade associations, a tech or business hub in your city.',
      'Ask for something specific. "Can I ask you three questions about how you priced your first contracts?" gets a yes more often than "Please mentor me."',
      'Give before you ask. Send a lead, share a supplier contact, give honest feedback on their page.',
      'Set a fixed rhythm: weekly with your accountability partner, monthly with your mentor, monthly with your peers.',
      'Prune. People who only discourage, or only cheer, are not support. Keep those who ask hard questions.',
    ] },
    { kind: 'callout', body: 'Family and friends love you, but they are rarely the right accountability partner. They forgive missed targets too easily. Choose someone who will ask for the number.' },
    { kind: 'text', body: 'Keep a simple log of who you spoke to and what changed because of it. If a month passes without one useful conversation, that is a signal to rebuild the circle, not to work harder alone.' },
  ],
  'Signs you are ready to quit, and signs you are not': [
    { kind: 'text', body: 'The worst day to decide is the day after a bad meeting with your boss. Frustration tells you that you want to leave. It does not tell you that the business can carry you. Use this checklist instead, and answer with numbers, not feelings.' },
    { kind: 'list', heading: 'Signs you are ready', items: [
      'The business has made steady revenue for at least six months, and profit already covers a large part of your essential monthly expenses.',
      'You have six to twelve months of essential personal expenses saved, separate from business money.',
      'Demand is limited by your time, not by customers. You are turning work down or delaying orders because of your job.',
      'Customers come back and refer others, not only friends and family.',
      'Health cover and a pension plan are arranged for life after the payslip.',
      'You know your exit terms: notice period, restrictions and final entitlements.',
      'Your spouse or household understands the plan and the budget.',
    ] },
    { kind: 'list', heading: 'Signs you are not ready yet', items: [
      'Sales spike and vanish, and you cannot say what next month will bring.',
      'Your main reason for leaving is a boss, a colleague or the traffic.',
      'Your savings would last less than three months.',
      'You plan to pay household bills from business capital or a loan.',
      'You have not tested whether more hours actually produce more sales.',
      'Most customers came through your employer, and your contract may restrict serving them.',
    ] },
    { kind: 'callout', body: 'Score yourself honestly. If you tick fewer than five of the seven ready signs, or any of the not-ready signs, do not resign yet. Set a date ninety days away to check again.' },
    { kind: 'text', body: 'Not ready does not mean never. Each gap has a fix: more savings, a sharper offer, a second way to find customers, or a part-time arrangement with your employer while you build. Write down the fix for each gap, with a date beside it, and work through the list.' },
  ],
  'Negotiate a part-time or contract exit': [
    { kind: 'text', body: 'Resigning outright is not the only exit. Some employers would rather keep part of your skill than lose all of it, especially if you hold knowledge that is hard to replace or a handover would take months. A gradual exit can pay you while the business grows.' },
    { kind: 'list', heading: 'Options you can propose', items: [
      'Reduced days: three or four days a week at a pro-rated salary.',
      'Fixed-term contract: you leave the staff list and return as a consultant for a defined project with an end date.',
      'Extended handover: a longer notice period with agreed hours, during which you train your replacement.',
      'Retainer: a monthly fee for being available for a set number of hours.',
    ] },
    { kind: 'steps', heading: 'Make the ask', items: [
      'Read your contract first. Know your notice period and any clause on outside business or competition.',
      'Pick your moment: after a delivery that went well, not in the middle of a crisis.',
      'Lead with their problem: continuity, handover risk, and the time and cost of hiring someone new.',
      'Put it in writing: one page with days, hours, deliverables, pay, duration and a review date.',
      'Decide in advance what you will do if they say no, so the answer does not push you into a rushed resignation.',
      'Get the final terms signed, not just agreed on a call with your line manager. Cover health insurance, pension, leave and who owns the work you produce.',
    ] },
    { kind: 'text', body: 'If you move from employee to contractor, your employer stops handling your tax and pension. You become responsible for both, so price your fee to cover them. Ask how payments will be processed for tax, and keep every invoice and any tax deduction receipt for your annual return.' },
    { kind: 'callout', body: 'Protect the business while you negotiate. Do not share customer details, pricing or plans that overlap with your employer. If your business could look like competition, get legal advice before you propose anything.' },
  ],
};
